<a href="https://colab.research.google.com/github/heddgehogg/Machine-Learning/blob/main/%D0%A9%D0%B5%D1%80%D0%B1%D0%B8%D0%BD%D0%B0_%D0%9B%D0%A0_1_%D0%A7%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Задати вектор, що складається з перших пʼяти натуральних чисел.

In [13]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
vector

array([1, 2, 3, 4, 5])

2. Транспортувати вектор.

In [7]:
v = np.matrix([1, 2, 3, 4, 5])
print(v)

v2 = v.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

3. Напишіть функцію, яка повертає вектор у зворотному напрямку.

In [8]:
v = np.array([1, 2, 3, 4, 5])
print(v[::-1])

[5 4 3 2 1]


4. Обчислити середнє значення вектора.

In [9]:
print(np.mean(v))

3.0


5. Знайти найбільший і найменший елементи вектора.

In [10]:
print(np.max(v))
print(np.min(v))

5
1


6. Обчислити скалярний добуток двох векторів.

In [11]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.dot(v1, v2))
print(v1*v2)

32
[ 4 10 18]


7. Напишіть функцію, яка нормалізує вектор.

In [15]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)
print(norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

8. Задайте два вектори. Визначте, чи є вони ортогональними.

In [16]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
np.dot(v1, v2)

np.int64(0)

9. Визначте унікальні елементи вектора.

In [17]:
v = np.array([1, 2, 3, 2, 4, 5, 3])
np.unique(v)

array([1, 2, 3, 4, 5])

10. Виконати операції над векторами.

In [18]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


11. Перевірити, чи дорівнює довжина вектора 5.

In [21]:
v = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(v)

np.isclose(length, 5)

np.False_

12. Задати матрицю, заповнену випадковими числами.

In [23]:
a = np.random.randint(0, 11, (3, 3))
a

array([[4, 7, 6],
       [9, 3, 3],
       [3, 7, 0]])

13. Обчислити визначник матриці.

In [24]:
np.linalg.det(a)

np.float64(303.00000000000017)

14. Знаходження оберненої матриці.

In [25]:
np.linalg.inv(a)

array([[-0.06930693,  0.13861386,  0.00990099],
       [ 0.02970297, -0.05940594,  0.13861386],
       [ 0.17821782, -0.02310231, -0.16831683]])

15. Розвʼяжіть систему лінійних рівнянь A*x=b, де A - матриця коефіцієнтів, b - вектор вільних членів.

In [28]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


16. Множення двох матриць.

In [29]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

np.dot(a, b)

array([-2, -6, 16])

17. Транспортування матриці.

In [30]:
print(a.T)
print(b.T)

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


18. Перевірка симетричіної матриці.

In [31]:
matrix = np.matrix([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
np.allclose(matrix, matrix.T)

True

19. Обчислення сліду матриці.

In [32]:
np.trace(matrix)

np.int64(6)

20. Провести операції над матрицями.

In [33]:
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


21. Піднесення матриці до ступеня.

In [34]:
a = np.matrix([[1, 2], [3, 4]])
np.linalg.matrix_power(a, 2)

matrix([[ 7, 10],
        [15, 22]])

22. Сортування рядків або стовпців матриці.

In [35]:
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 2]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 2]]
[[2 2 2]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 2 3]]
[[2 2 2 3 3 3 4 5 5]]


23. Підрахуй суму елементів кожного рядка матриці.

In [36]:
row_sums = np.sum(a, axis=1).reshape(-1, 1)

print('Сума елеменітв кожного рядка:')
print(row_sums)

Сума елеменітв кожного рядка:
[[3]
 [7]]
