In [2]:
import numpy as np

## **Варіант 22**

### Завдання 1

22. Створіть одновимірний масив (вектор) зі значеннями 𝑒^𝑥 для кожного натурального
числа x, починаючи з 1, та виведіть його значення.

In [15]:
n = 10
x = np.arange(1, n+1)
vector = np.exp(x)

print("Натуральні числа:", x)
print("Вектор e^x:\n", vector)

Натуральні числа: [ 1  2  3  4  5  6  7  8  9 10]
Вектор e^x:
 [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


### Завдання 2

22. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його тангенсами
кожного натурального числа, починаючи з 1, та виведіть його значення.

In [17]:
s = np.arange(1, 10).reshape(3, 3)
print("Матриця:\n", s)
m = np.tan(s)

print("\nМатриця з тангенсів:\n", m)


Матриця:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Матриця з тангенсів:
 [[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


### Завдання 3

22. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами від -1 до
1 та виведіть непарні числа.

In [19]:
m = np.random.uniform(-1, 2, (3, 3))

rounded = np.round(m).astype(int)
even_numbers = rounded[rounded % 2 == 0]

print("Матриця:\n", m)
print("Після округлення:\n", rounded)
print("Парні числа:\n", even_numbers)

Матриця:
 [[ 0.68051855 -0.84613806  0.20879407]
 [-0.33850175  1.53036022 -0.23831514]
 [ 1.53285815  0.64751525  1.40797513]]
Після округлення:
 [[ 1 -1  0]
 [ 0  2  0]
 [ 2  1  1]]
Парні числа:
 [0 0 2 0 2]


### Завдання 4

22. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.8
до 0.8 та виведіть його значення.

In [22]:
m = np.random.uniform(-0.8, 0.8, (4, 4))
print(m)

[[ 0.51616487 -0.07721136 -0.56568296 -0.27898923]
 [-0.17984268  0.59078267  0.76226584  0.20733708]
 [-0.51702853  0.13603547  0.38938771  0.39072683]
 [-0.00894459  0.01180388 -0.53954394  0.37184713]]


### Завдання 5

22. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими
числами в діапазоні від 5 до 15 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [23]:
arr1 = np.random.randint(5, 16, 6)
arr2 = np.random.randint(5, 16, 6)

add = arr1 + arr2
subt = arr1 - arr2
mul = arr1 * arr2

print("Масив 1:", arr1)
print("Масив 2:", arr2)
print("Додавання:", add)
print("Віднімання:", subt)
print("Множення:", mul)

Масив 1: [12  9 15 14  5 12]
Масив 2: [ 9 11 14  8  6  7]
Додавання: [21 20 29 22 11 19]
Віднімання: [ 3 -2  1  6 -1  5]
Множення: [108  99 210 112  30  84]


### Завдання 6

22. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -6 до 6 та
знайдіть їх добуток.

In [31]:
a = np.random.randint(-6, 7, (4, 4))
b = np.random.randint(-6, 7, (4, 4))

print("A:\n", a, "\nB:\n", b, "\nA*B:\n", np.dot(a, b), "\n")

A:
 [[ 5  4 -2  6]
 [ 4  6  1  1]
 [-4  1  2 -1]
 [-1  6  2 -1]] 
B:
 [[ 6  2 -2 -2]
 [ 6  2  3  5]
 [ 3 -3  5 -5]
 [ 6  6  1 -2]] 
A*B:
 [[ 84  60  -2   8]
 [ 69  23  16  15]
 [-18 -18  20   5]
 [ 30  -2  29  24]] 



### Завдання 7

22. Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 8 та перемножте їх між собою.

In [3]:
a = np.random.randint(1, 9, (3, 2))
b = np.random.randint(1, 9, (2, 2))

print("A:\n", a, "\nB:\n", b, "\nA*B:\n", np.dot(a, b), "\n")

A:
 [[8 4]
 [5 5]
 [5 3]] 
B:
 [[6 4]
 [5 4]] 
A*B:
 [[68 48]
 [55 40]
 [45 32]] 



### Завдання 8

22. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 8 та знайдіть її обернену матрицю.

In [11]:
a = np.random.randint(1, 9, (3, 3))
print("Матриця А:\n", a)

a_inv = np.linalg.inv(a)
print("\nОбернена матриця до матриці A:\n", a_inv)

Матриця А:
 [[7 1 3]
 [7 7 4]
 [5 8 3]]

Обернена матриця до матриці A:
 [[ 0.73333333 -1.4         1.13333333]
 [ 0.06666667 -0.4         0.46666667]
 [-1.4         3.4        -2.8       ]]


### Завдання 9

22. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та транспонуйте її.

In [20]:
m = np.random.uniform(-1, 1, (4, 4))
print("Матриця:\n", m)
transposed = m.T

print("\nТранспонована матриця:\n", transposed)

Матриця:
 [[ 0.65155751  0.76258561  0.80216567  0.31747663]
 [-0.53657171  0.92706513 -0.1639757   0.32164428]
 [ 0.86792412  0.24593925  0.4991487   0.18615126]
 [ 0.57977231  0.98895067  0.76725122 -0.96602291]]

Транспонована матриця:
 [[ 0.65155751 -0.53657171  0.86792412  0.57977231]
 [ 0.76258561  0.92706513  0.24593925  0.98895067]
 [ 0.80216567 -0.1639757   0.4991487   0.76725122]
 [ 0.31747663  0.32164428  0.18615126 -0.96602291]]


### Завдання 10

22. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [31]:
m = np.random.rand(3, 4)
v = np.random.randint(1, 11, (4, 1))

print("Матриця A:\n", m)
print("\nВектор v:\n", v)

prod = np.dot(m, v)
print("\nДобуток A * v:\n", prod)

Матриця A:
 [[0.30771304 0.00667758 0.73447764 0.11822263]
 [0.32657173 0.57277542 0.70101089 0.18610185]
 [0.60872832 0.65511696 0.24625466 0.23672809]]

Вектор v:
 [[4]
 [3]
 [5]
 [5]]

Добуток A * v:
 [[5.51438626]
 [7.46017686]
 [6.81517794]]


### Завдання 11

22. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [30]:
m = np.random.randint(1, 11, (2, 3))
v = np.random.rand(3)

print("Матриця A:\n", m)
print("\nВектор v:\n", v)

prod = np.dot(m, v)
print("\nДобуток A * v:\n", prod)

Матриця A:
 [[9 6 5]
 [4 8 7]]

Вектор v:
 [0.86157416 0.08403006 0.41158883]

Добуток A * v:
 [10.31629196  6.99965894]


### Завдання 12

22. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 3 та знайдіть суму всіх елементів другої матриці.

In [28]:
a = np.random.randint(1, 4, (3, 3))
b = np.random.randint(1, 4, (3, 3))
print("A:\n", a, "\nB:\n", b)

sum_b = np.sum(b)
print("\nСума всіх елементів матриці B:", sum_b)

A:
 [[3 2 1]
 [3 1 3]
 [3 1 3]] 
B:
 [[2 3 2]
 [1 1 1]
 [1 1 2]]

Сума всіх елементів матриці B: 14


### Завдання 13

22. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть суму їх елементів.

In [23]:
a = np.random.randint(1, 6, (3, 3))
b = np.random.randint(1, 6, (3, 3))

print("A:\n", a, "\nB:\n", b, "\nA+B:\n", a+b, "\n")

A:
 [[1 4 3]
 [3 1 1]
 [1 3 1]] 
B:
 [[4 1 5]
 [3 1 2]
 [1 3 2]] 
A+B:
 [[5 5 8]
 [6 2 3]
 [2 6 3]] 



### Завдання 14

22. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть суму елементів на головній діагоналі.

In [22]:
m = np.random.randint(1, 11, (3, 3))
print("Матриця А:\n", m)

diag_sum = np.trace(m)
print("\nСума елементів головної діагоналі:", diag_sum)

Матриця А:
 [[9 4 7]
 [4 9 1]
 [1 3 4]]

Сума елементів головної діагоналі: 22


### Завдання 15

22. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів
кожного стовпця матриці.

In [21]:
m = np.random.uniform(-1, 1, (3, 3))
print("Матриця А:\n", m)

prod = np.prod(m, axis=0)
vector = prod.reshape(-1, 1)

print("\nДобутки елементів по стовпцях (вектор-стовпчик):")
print(vector)

Матриця А:
 [[ 0.4237678  -0.38478106  0.03989156]
 [-0.55210689 -0.70176341 -0.21493364]
 [-0.71146753  0.24034725  0.25278513]]

Добутки елементів по стовпцях (вектор-стовпчик):
[[ 0.16645859]
 [ 0.06489983]
 [-0.00216739]]
